osx_image: xcode9.1
language: objective-c
branches:
  only:
    - master
before_install:
    - gem install xcpretty
before_script:
    - set -o pipefail
script:
    - xcodebuild test -project ./ProcessingKit.xcodeproj -scheme ProcessingKitTests -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.3.1,name=iPhone 7' | xcpretty -c
    - xcodebuild -project ./ProcessingKit.xcodeproj -scheme 'ProcessingKit OSX' -configuration Debug | xcpretty -c
after_success:
    - bash <(curl -s https://codecov.io/bash)
